### ISSUE TITLE
运行bert_re报错

### ISSUE THREAD

**Issue by andong0323** [taishan1994/pytorch_triple_extraction#11]
cd pytorch_triple_extraction/bert_re
bash run.sh
出现如下错误：
<img width="1618" alt="截屏2022-06-26 下午8 46 04" src="https://user-images.githubusercontent.com/37055147/175814874-400d2193-2665-4a45-acae-9c82e6d66111.png">
修改run.sh参数num_tags=49，出现如下错误：
<img width="1485" alt="截屏2022-06-26 下午8 47 17" src="https://user-images.githubusercontent.com/37055147/175814915-bc07757d-c86b-4cf7-9dfa-d53a124714c4.png">
能抽出时间看下具体原因吗？

**Comment by taishan1994** [comment]
> cd pytorch_triple_extraction/bert_re bash run.sh 出现如下错误： <img alt="截屏2022-06-26 下午8 46 04" width="1618" src="https://user-images.githubusercontent.com/37055147/175814874-400d2193-2665-4a45-acae-9c82e6d66111.png"> 修改run.sh参数num_tags=49，出现如下错误： <img alt="截屏2022-06-26 下午8 47 17" width="1485" src="https://user-images.githubusercontent.com/37055147/175814915-bc07757d-c86b-4cf7-9dfa-d53a124714c4.png"> 能抽出时间看下具体原因吗？

分别打印一下seq_out，ids和batch_size

> cd pytorch_triple_extraction/bert_re bash run.sh 出现如下错误： <img alt="截屏2022-06-26 下午8 46 04" width="1618" src="https://user-images.githubusercontent.com/37055147/175814874-400d2193-2665-4a45-acae-9c82e6d66111.png"> 修改run.sh参数num_tags=49，出现如下错误： <img alt="截屏2022-06-26 下午8 47 17" width="1485" src="https://user-images.githubusercontent.com/37055147/175814915-bc07757d-c86b-4cf7-9dfa-d53a124714c4.png"> 能抽出时间看下具体原因吗？

看下ids里面的标签是否超过了规定的句子的最大长度。

**Comment by andong0323** [comment]
您好，我跑的数据是代码库提供的数据。

**Comment by taishan1994** [comment]
> 您好，我跑的数据是代码库提供的数据。

对呀，打印一下seq_out的形状，ids，batch_size

**Comment by taishan1994** [comment]
> 您好，我跑的数据是代码库提供的数据。

这个问题可能是加载数据内存不够，我修改了数据处理方式，现在应该可以了。
