### ISSUE TITLE
关于bert_ner_model中num_tags

### ISSUE THREAD

**Issue by kol66** [taishan1994/pytorch_triple_extraction#12]

**Comment by kol66** [comment]
手快点了提交issue，不好意思。只能在这提问了，你好作者，请问
![image](https://user-images.githubusercontent.com/97020095/175954871-962e2c68-45bf-4bca-a5cc-3295c0b5b14e.png)
这里的nu'mnum.tags=33是哪个标签的数量呢？

**Comment by taishan1994** [comment]
> 手快点了提交issue，不好意思。只能在这提问了，你好作者，请问 ![image](https://user-images.githubusercontent.com/97020095/175955103-0d84bc1d-3ba6-49f8-bc85-7a4de547098b.png)
> 
> 这里的nu'mnum.tags=33是哪个标签的数量呢？

你这个是哪个文件里面的额。

**Comment by kol66** [comment]
好的，感谢回复！另外，还有一个问题请教您，我把数据换成自己的，格式还是和您的一样。在NER训练中，eval的accuracy从第一个epoch到最后一个epoch都是0.82左右（每10步eval一次），请问这是什么情况导致呢？
第一个：
![ZUPL_75J6}Z5Y{5V))QBCUL](https://user-images.githubusercontent.com/97020095/176217997-cdf86f6c-9554-42bf-90a5-afa6f1ad5967.png)
第二个：
![{$MAEIEL1 FU}J8ZR SC%L3](https://user-images.githubusercontent.com/97020095/176218011-26d928bd-506d-4426-9e32-0e4eb60a7f4a.png)

**Comment by taishan1994** [comment]
> 好的，感谢回复！另外，还有一个问题请教您，我把数据换成自己的，格式还是和您的一样。在NER训练中，eval的accuracy从第一个epoch到最后一个epoch都是0.82左右（每10步eval一次），请问这是什么情况导致呢？ 第一个： ![ZUPL_75J6}Z5Y{5V))QBCUL](https://user-images.githubusercontent.com/97020095/176217997-cdf86f6c-9554-42bf-90a5-afa6f1ad5967.png) 第二个： ![{$MAEIEL1 FU}J8ZR SC%L3](https://user-images.githubusercontent.com/97020095/176218011-26d928bd-506d-4426-9e32-0e4eb60a7f4a.png)

训练的数据量有多少，参数是什么贴一下。

**Comment by taishan1994** [comment]
> > 好的，感谢回复！另外，还有一个问题请教您，我把数据换成自己的，格式还是和您的一样。在NER训练中，eval的accuracy从第一个epoch到最后一个epoch都是0.82左右（每10步eval一次），请问这是什么情况导致呢？ 第一个： ![ZUPL_75J6}Z5Y{5V))QBCUL](https://user-images.githubusercontent.com/97020095/176217997-cdf86f6c-9554-42bf-90a5-afa6f1ad5967.png) 第二个： ![{$MAEIEL1 FU}J8ZR SC%L3](https://user-images.githubusercontent.com/97020095/176218011-26d928bd-506d-4426-9e32-0e4eb60a7f4a.png)
> 
> 训练的数据量有多少，参数是什么贴一下。可能需要使用更多的epoch训练。

**Comment by kol66** [comment]
你好，我的训练数据700多条，训练了15个epoch，但是eval的accuracy都是在0.83浮动，下图是参数
![image](https://user-images.githubusercontent.com/97020095/176372811-91c0452a-2115-4f2a-ac0e-103767fb9b71.png)

**Comment by taishan1994** [comment]
> 你好，我的训练数据700多条，训练了15个epoch，但是eval的accuracy都是在0.83浮动，下图是参数 ![image](https://user-images.githubusercontent.com/97020095/176372811-91c0452a-2115-4f2a-ac0e-103767fb9b71.png)

你把保存的模型用来预测看看效果怎么样。

**Comment by taishan1994** [comment]
> 做单句预测时，三对标签能预测对两对。计算保存的模型指标如下图 ![image](https://user-images.githubusercontent.com/97020095/176635626-43089d7a-f144-4dcd-aec2-ed4b36b2ff48.png) 感觉这些指标都算正常，因为我数据标注质量可能不高，就是但是eval的accuracy都是在0.82浮动，不知道该如何解释呢？

一般情况下是不看accuracy的，看的是f1-score。

**Comment by kol66** [comment]
好的，谢谢回复！
