### ISSUE TITLE
关于关系抽取训练

### ISSUE THREAD

**Issue by kol66** [taishan1994/pytorch_triple_extraction#13]
我用您的程序训练了自己的数据，数据格式全部都是和您的一样，参数只修改了bert_re/bert_config.py中24行的num_tags，我改为num_tags=6
关系类别如下
![image](https://user-images.githubusercontent.com/97020095/176641733-b7d3a193-557c-4625-900d-8a671a7f6710.png)
在GPU训练过程中遇到了如下错误：
![image](https://user-images.githubusercontent.com/97020095/176641951-84884d28-798e-4a1a-9eb5-b00dd6354dc5.png)
换用CPU训练报错如下：
![image](https://user-images.githubusercontent.com/97020095/176643731-e27e8f11-5f3f-4d04-bd03-2ed46ea44363.png)
网上说的最多的是分类数填错了，但是num_tags=6或5都试过了，都没解决。您有遇到这种情况嘛？还麻烦您解答一下，谢谢！

**Comment by kol66** [comment]
作者您好，用您的数据集训练，啥都没改，也出现了这个问题

**Comment by taishan1994** [comment]
> 作者您好，用您的数据集训练，啥都没改，也出现了这个问题

用的数据是主目录的data，有个re_mid_data/rels.txt，里面最后有个空类别，因此num_tags=实际类别+1。

**Comment by kol66** [comment]
对的，我就是用的主目录的data，nun-tags也加一了，还是不行，跑您的数据也是一样的报错

**Comment by kol66** [comment]
您好，刚刚试了pytorch==1.6.0，transformers==4.5.0，跑您的数据还是一样的报错，，，太难啦呜呜呜

**Comment by taishan1994** [comment]
> 您好，刚刚试了pytorch==1.6.0，transformers==4.5.0，跑您的数据还是一样的报错，，，太难啦呜呜呜

使用命令行运行，不要在pycharm里面直接运行呢？

**Comment by kol66** [comment]
你好，我的环境是：Python 3.7, CUDA 10.2, cuDNN 7.6, Pytorch 1.6.0, transformers 4.5.0 , 请问会不会是cuda的版本问题呢？您的cuda版本是？

**Comment by taishan1994** [comment]
> 你好，我的环境是：Python 3.7, CUDA 10.2, cuDNN 7.6, Pytorch 1.6.0, transformers 4.5.0 , 请问会不会是cuda的版本问题呢？您的cuda版本是？

加我微信：15926459981

**Comment by kol66** [comment]
感谢，已添加
