### ISSUE TITLE
训练好的模型在测试时发生了维度错误。

### ISSUE THREAD

**Issue by Lv-shuai** [taishan1994/pytorch_triple_extraction#16]
![屏幕截图 2022-10-15 010322](https://user-images.githubusercontent.com/101809034/195902382-5adc11c0-4cb9-40ba-9930-0e4bace6e249.png)
chinese-bert-wwm-ext与chinese-roberta-wwm-ext里面的文件是一样的吗？我看他们的大小都相同。

**Comment by Lv-shuai** [comment]
我将train batch和test batch都改成了1，是这个原因吗

**Comment by taishan1994** [comment]
> ![屏幕截图 2022-10-15 010322](https://user-images.githubusercontent.com/101809034/195902382-5adc11c0-4cb9-40ba-9930-0e4bace6e249.png) chinese-bert-wwm-ext与chinese-roberta-wwm-ext里面的文件是一样的吗？我看他们的大小都相同。

应该是一样的。

**Comment by taishan1994** [comment]
> 我将train batch和test batch都改成了1，是这个原因吗

要先确保数据的长度都在设置的最大长度内。

**Comment by Lv-shuai** [comment]
> > 我将train batch和test batch都改成了1，是这个原因吗
> 
> 要先确保数据的长度都在设置的最大长度内。

**Comment by Lv-shuai** [comment]
数据是题目里的数据，进过process.py操作，分割成的train和eval。数据的长度应该都在最大长度512以内吧。

**Comment by taishan1994** [comment]
> 数据是题目里的数据，进过process.py操作，分割成的train和eval。数据的长度应该都在最大长度512以内吧。

你可以打印下报错的那个地方的两个数据的维度看看先。

**Comment by Lv-shuai** [comment]
> 

您好，我发现在测试的时候，true_label和tmp_batch_true_all的维度不一样，比如（265，258），（265，512）。tmp_batch_true_all这个数据使我们预测得到标签吗？是不是应该都处理成265。

**Comment by Lv-shuai** [comment]
您的numpy版本是多少？ 下面这个问题我感觉是numpy版本原因。
![屏幕截图 2022-10-15 234850](https://user-images.githubusercontent.com/101809034/195995735-cd145261-7a42-4f62-ac91-350ed57256b0.png)

**Comment by taishan1994** [comment]
> 您的numpy版本是多少？ 下面这个问题我感觉是numpy版本原因。 ![屏幕截图 2022-10-15 234850](https://user-images.githubusercontent.com/101809034/195995735-cd145261-7a42-4f62-ac91-350ed57256b0.png)

1.21.6

**Comment by shunmine00** [comment]
> ![屏幕截图 2022-10-15 010322](https://user-images.githubusercontent.com/101809034/195902382-5adc11c0-4cb9-40ba-9930-0e4bace6e249.png) chinese-bert-wwm-ext与chinese-roberta-wwm-ext里面的文件是一样的吗？我看他们的大小都相同。

您好，请问您解决这个问题了吗？我遇到了相同的问题。

**Comment by Lv-shuai** [comment]
> > ![屏幕截图 2022-10-15 010322](https://user-images.githubusercontent.com/101809034/195902382-5adc11c0-4cb9-40ba-9930-0e4bace6e249.png) chinese-bert-wwm-ext与chinese-roberta-wwm-ext里面的文件是一样的吗？我看他们的大小都相同。
> 
> 您好，请问您解决这个问题了吗？我遇到了相同的问题。

你重新设置一下那两个权重文件夹，或者看看你的环境。可能是环境不一样，有的包版本问题。
