### ISSUE TITLE
训练模型

### ISSUE THREAD

**Issue by sdutgt** [taishan1994/pytorch_triple_extraction#17]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/93463681/195980525-ab7f4b04-8494-44da-b3ed-2dc95e11ac31.png">

在训练关系抽取的时候会出现list index out of range问题，想问一下，这个要从哪里去解决呢，我不太清楚这个list是从哪里传过来的

**Comment by taishan1994** [comment]
> <img alt="image" width="964" src="https://user-images.githubusercontent.com/93463681/195980525-ab7f4b04-8494-44da-b3ed-2dc95e11ac31.png">
> 
> 在训练关系抽取的时候会出现list index out of range问题，想问一下，这个要从哪里去解决呢，我不太清楚这个list是从哪里传过来的

具体是哪里报的错。

**Comment by sdutgt** [comment]
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/93463681/196008815-7f1557ca-68d4-4511-bd0e-d2ec27ed1aab.png">
在main中进行trainer.test()时，出现这个样子

**Comment by taishan1994** [comment]
> <img alt="image" width="1312" src="https://user-images.githubusercontent.com/93463681/196008815-7f1557ca-68d4-4511-bd0e-d2ec27ed1aab.png">
> 
> 在main中进行trainer.test()时，出现这个样子

测试时打印一下batch_token_ids的形状看看。

**Comment by sdutgt** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/93463681/196015064-59630aa4-4802-4ade-84f9-acb535e8e0e4.png">
出来的是这个，现在我好像有些蒙圈了，不清楚这个是啥意思了

**Comment by taishan1994** [comment]
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/93463681/196015064-59630aa4-4802-4ade-84f9-acb535e8e0e4.png">
> 
> 出来的是这个，现在我好像有些蒙圈了，不清楚这个是啥意思了

为啥有的是数字 有的是张量

**Comment by sdutgt** [comment]
我没有用cuda，是因为这个原因产生的结果吗？

**Comment by pergrand** [comment]
解决了吗， 同样是这个问题，

**Comment by taishan1994** [comment]
> 解决了吗， 同样是这个问题，

你们用的哪个数据集额，我这都没问题。。
![image](https://user-images.githubusercontent.com/27845149/205628518-0e3436a7-593d-433f-9571-2573b8de7d13.png)

**Comment by Lv-shuai** [comment]
> <img alt="image" width="1312" src="https://user-images.githubusercontent.com/93463681/196008815-7f1557ca-68d4-4511-bd0e-d2ec27ed1aab.png">
> 
> 在main中进行trainer.test()时，出现这个样子

兄弟，解决了吗

**Comment by Lv-shuai** [comment]
> > 解决了吗， 同样是这个问题，
> 
> 你们用的哪个数据集额，我这都没问题。。 ![image](https://user-images.githubusercontent.com/27845149/205628518-0e3436a7-593d-433f-9571-2573b8de7d13.png)

哎、您这里测试怎么只有166的数据，我们都是1223的。

**Comment by Lv-shuai** [comment]
> > > 解决了吗， 同样是这个问题，
> > 
> > 
> > 你们用的哪个数据集额，我这都没问题。。 ![image](https://user-images.githubusercontent.com/27845149/205628518-0e3436a7-593d-433f-9571-2573b8de7d13.png)
> 
> 哎、您这里测试怎么只有166的数据，我们都是1223的。

我知道了，您这个166的测试数据，是去掉了所有故障类型为”未知“的数据。

**Comment by BIGBIGMAN233** [comment]
那这个最后怎么解决的？

**Comment by Lv-shuai** [comment]
> 那这个最后怎么解决的？
看你的数据，里面可能有哪一条不合适。
