### ISSUE TITLE
请问下torchcrf是哪个版本

### ISSUE THREAD

**Issue by risotoonero** [taishan1994/pytorch_triple_extraction#19]

**Comment by taishan1994** [comment]
> _No description provided._

0.7.2

**Comment by risotoonero** [comment]
![image](https://user-images.githubusercontent.com/80516074/202470120-23fdb53a-cfb3-4e45-9bd3-7972331d0581.png)
大佬，我想问问这怎么解决

**Comment by taishan1994** [comment]
> ![image](https://user-images.githubusercontent.com/80516074/202470120-23fdb53a-cfb3-4e45-9bd3-7972331d0581.png) 大佬，我想问问这怎么解决

检查下数据的长度是否和attention_mask的长度一致，同时不能用长度为0的数据。
