### ISSUE TITLE
关于关系抽取的数据标注问题

### ISSUE THREAD

**Issue by shitft** [taishan1994/pytorch_triple_extraction#20]
大佬，我是从您的实体识别项目过来的，请问您的cner数据集要怎么转换为这个项目里面的输入格式呀

**Comment by taishan1994** [comment]
> 大佬，我是从您的实体识别项目过来的，请问您的cner数据集要怎么转换为这个项目里面的输入格式呀

cner只有实体抽取，没有关系抽取这一步额。

**Comment by shitft** [comment]
BIO序列标注数据可以转换为您关系识别里的那种文件格式咩，感觉再次手动标注时间有点伤不起



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 西西嘛呦 ***@***.***&gt;
发送时间: 2022年11月29日 20:35
收件人: taishan1994/pytorch_triple_extraction ***@***.***&gt;
抄送: shitft ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[taishan1994/pytorch_triple_extraction] 关于关系抽取的数据标注问题 (Issue #20)





  
大佬，我是从您的实体识别项目过来的，请问您的cner数据集要怎么转换为这个项目里面的输入格式呀
  
cner只有实体抽取，没有关系抽取这一步额。

**Comment by taishan1994** [comment]
> BIO序列标注数据可以转换为您关系识别里的那种文件格式咩，感觉再次手动标注时间有点伤不起 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 西西嘛呦 ***@***.***&gt; 发送时间: 2022年11月29日 20:35 收件人: taishan1994/pytorch_triple_extraction ***@***.***&gt; 抄送: shitft ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[taishan1994/pytorch_triple_extraction] 关于关系抽取的数据标注问题 (Issue #20) 大佬，我是从您的实体识别项目过来的，请问您的cner数据集要怎么转换为这个项目里面的输入格式呀 cner只有实体抽取，没有关系抽取这一步额。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你都不知道里面哪些实体之间是具有关系的，不好转换，为啥不用标准的关系抽取数据集。

**Comment by taishan1994** [comment]
> 因为我是在我自己的标注的数据集上跑的，您的cner和我的数据格式差不多，我看了很多开源代码，好像都不能直接用序列标注的数据集来进行关系识别 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 西西嘛呦 ***@***.***&gt; 发送时间: 2022年11月29日 20:41 收件人: taishan1994/pytorch_triple_extraction ***@***.***&gt; 抄送: shitft ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[taishan1994/pytorch_triple_extraction] 关于关系抽取的数据标注问题 (Issue #20) BIO序列标注数据可以转换为您关系识别里的那种文件格式咩，感觉再次手动标注时间有点伤不起 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: 西西嘛呦 @.&gt; 发送时间: 2022年11月29日 20:35 收件人: taishan1994/pytorch_triple_extraction @.&gt; 抄送: shitft @.&gt;, Author @.&gt; 主题: 回复：[taishan1994/pytorch_triple_extraction] 关于关系抽取的数据标注问题 (Issue #20) 大佬，我是从您的实体识别项目过来的，请问您的cner数据集要怎么转换为这个项目里面的输入格式呀 cner只有实体抽取，没有关系抽取这一步额。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 你都不知道里面哪些实体之间是具有关系的，不好转换，为啥不用标准的关系抽取数据集。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

标注的时候就应该标明实体以及关系。。。
