### ISSUE TITLE
运行bert_re文件夹下的main的问题

### ISSUE THREAD

**Issue by BIGBIGMAN233** [taishan1994/pytorch_triple_extraction#22]
![image](https://user-images.githubusercontent.com/119472061/218308181-0f190482-1138-4527-8b20-c5c7c644dbef.png)
![image](https://user-images.githubusercontent.com/119472061/218308227-bec5d1eb-21b0-441c-9eb6-ada992b818aa.png)
@taishan1994 博主您好，我明明已经跑了一半，突然报错。打印了以下batch_token_ids，发现是空的。

**Comment by taishan1994** [comment]
> ![image](https://user-images.githubusercontent.com/119472061/218308181-0f190482-1138-4527-8b20-c5c7c644dbef.png) ![image](https://user-images.githubusercontent.com/119472061/218308227-bec5d1eb-21b0-441c-9eb6-ada992b818aa.png) @taishan1994 博主您好，我明明已经跑了一半，突然报错。打印了以下batch_token_ids，发现是空的。

看是不是数据的问题，或者可以在train的时候做个异常处理，如果batch_token_ids是空的则继续。
