### ISSUE TITLE
特征融合

### ISSUE THREAD

**Issue by AIwjy94** [taishan1994/pytorch_triple_extraction#24]
def transforme_re_data(subjects, objects, text):

遍历每一个主体和客体
这下面的函数可否讲解一下

**Comment by taishan1994** [comment]
> def transforme_re_data(subjects, objects, text):
> 
> 遍历每一个主体和客体 这下面的函数可否讲解一下

因为主客体可能会有包含的地方，因此先做个比较，然后先把长的用特殊字符替换，再把短的用特殊字符替换。最后再重新计算索引，恢复原来的文本。如果不存在包含的情况，就直接在主客体左右添加特殊符号，然后重新计算索引就行了。
