### ISSUE TITLE
这个三元组任务是用了两个模型吗？

### ISSUE THREAD

**Issue by Violettttee** [taishan1994/pytorch_triple_extraction#31]
您好，想请问下这个三元组任务是不是使用了两个模型？一个用于命名体识别，另一个用于实体关系抽取？是否有用一个模型进行三元组任务训练的呢？如果用一个模型的话，是否分别指定两个损失函数、两个全连接层即可？

**Comment by taishan1994** [comment]
直接用global_pointer或者casrel

**Comment by Violettttee** [comment]
> 直接用global_pointer或者casrel
请问这种三元组提取的方式能粗粒度到识别实体的具体分类，而不只是主体和客体吗？比如您的Onerel的模型代码，把三元组作为一个三维矩阵的话，是否不太能识别命名实体的分类？
