### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by chenjiawei22** [taishan1994/pytorch_triple_extraction#5]
你好，能给出数据的格式吗？还有就是
![image](https://user-images.githubusercontent.com/44490828/158321697-ad0d669b-4a7f-4003-8894-df456b5c8b62.png)
这两个文件的的内容

**Comment by taishan1994** [comment]
> 你好，能给出数据的格式吗？还有就是 ![image](https://user-images.githubusercontent.com/44490828/158321697-ad0d669b-4a7f-4003-8894-df456b5c8b62.png) 这两个文件的的内容

在下载的数据里面有吧，没有的话参照bert_bilstm_crf_ner下preprocess.py处理
