### ISSUE TITLE
AssertionError: pretrained bert file does not exist

### ISSUE THREAD

**Issue by newbieonCV** [taishan1994/pytorch_triple_extraction#6]

**Comment by newbieonCV** [comment]
assert os.path.exists(bert_dir) and os.path.exists(config_path), \
            'pretrained bert file does not exist'

**Comment by taishan1994** [comment]
> assert os.path.exists(bert_dir) and os.path.exists(config_path), 'pretrained bert file does not exist'

预训练的模型下载好放在指定的位置。

**Comment by newbieonCV** [comment]
谢谢您的回复，这个问题解决了
