### ISSUE TITLE
data

### ISSUE THREAD

**Issue by newbieonCV** [taishan1994/pytorch_triple_extraction#9]
博主，很感谢之前您的解答，代码跑出来了。目前我想自己标注些数据，但是对于data下的文件的作用不是很清楚，您可以简单的说说吗？

**Comment by taishan1994** [comment]
> 博主，很感谢之前您的解答，代码跑出来了。目前我想自己标注些数据，但是对于data下的文件的作用不是很清楚，您可以简单的说说吗？

实体识别的还是关系抽取的

**Comment by newbieonCV** [comment]
关于实体识别的
此外，就是您在关系抽取的时候是只用了bert吗

**Comment by taishan1994** [comment]
> 关于实体识别的 此外，就是您在关系抽取的时候是只用了bert吗

实体识别点进去有个链接说明。关系抽取就只用了bert。
